name: trojai_rl
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.6.15=py38h06a4308_0
  - cffi=1.15.1=py38h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=37.0.1=py38h9ce1e76_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.4.0=hecacb30_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1q=h7f8727e_0
  - pillow=9.2.0=py38hace64e9_1
  - pip=22.1.2=py38h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - pytorch=1.12.1=py3.8_cuda10.2_cudnn7.6.5_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py38h06a4308_0
  - setuptools=61.2.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py38_cu102
  - torchvision=0.13.1=py38_cu102
  - typing_extensions=4.3.0=py38h06a4308_0
  - urllib3=1.26.11=py38h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==1.2.0
      - ale-py==0.7.5
      - atari-py==0.2.9
      - attrs==23.1.0
      - cachetools==5.2.0
      - cloudpickle==1.2.2
      - cycler==0.11.0
      - fonttools==4.36.0
      - future==0.18.2
      - google-auth==2.10.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.47.0
      - gym==0.15.3
      - gym-minigrid==1.0.2
      - gym-notices==0.0.8
      - imageio==2.21.1
      - importlib-metadata==4.12.0
      - importlib-resources==5.9.0
      - joblib==1.1.0
      - jsonpickle==3.0.1
      - jsonschema==4.18.2
      - jsonschema-specifications==2023.6.1
      - kiwisolver==1.4.4
      - markdown==3.4.1
      - markupsafe==2.1.1
      - matplotlib==3.5.3
      - networkx==2.8.5
      - numpy==1.17.4
      - oauthlib==3.2.0
      - opencv-python==4.6.0.66
      - packaging==21.3
      - pandas==1.3.5
      - pkgutil-resolve-name==1.3.10
      - protobuf==3.19.4
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pygame==2.1.0
      - pyglet==1.3.2
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2022.2.1
      - pywavelets==1.3.0
      - referencing==0.29.1
      - requests-oauthlib==1.3.1
      - rpds-py==0.8.10
      - rsa==4.9
      - scikit-image==0.19.3
      - scikit-learn==1.1.2
      - scipy==1.8.1
      - stable-baselines==2.10.2
      - tb-nightly==2.11.0a20220818
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - torch-ac==1.1.0
      - tqdm==4.64.0
      - trojai-rl==0.1.1
      - werkzeug==2.2.2
      - zipp==3.8.1
